### ISSUE TITLE
not receiving initial connected event for an output port

### ISSUE THREAD

**Issue by belm0** [cotejp/webmidi#24] opened 2017-10-15 04:00 UTC
I have a MIDI controller which happens to also posses an output port for configuration.

When I enable WebMidi I only receive a connected event for the input port.  Subsequently disconnecting the device, I do received disconnected events for input & output, and again receive both when I reconnect.

Following is logging of WebMidi events.

```
[enable WebMidi with device already connected]
{timestamp: 74.58000000000001, type: "connected", id: "-1075253572", manufacturer: "AKAI", name: "MPKmini2", …}id: "-1075253572"input: Input {_userHandlers: {…}, _midiInput: MIDIInput, …}manufacturer: "AKAI"name: "MPKmini2"timestamp: 74.58000000000001type: "connected"__proto__: Object

[disconnect device]
{timestamp: 2325.8300000000004, type: "disconnected", id: "-1075253572", manufacturer: "AKAI", name: "MPKmini2"}id: "-1075253572"manufacturer: "AKAI"name: "MPKmini2"timestamp: 2325.8300000000004type: "disconnected"__proto__: Object
{timestamp: 2327.4900000000002, type: "disconnected", id: "898669612", manufacturer: "AKAI", name: "MPKmini2"}id: "898669612"manufacturer: "AKAI"name: "MPKmini2"timestamp: 2327.4900000000002type: "disconnected"__proto__: Object

[reconnect device]
{timestamp: 39933.12, type: "connected", id: "898669612", manufacturer: "AKAI", name: "MPKmini2", …}
{timestamp: 39934.82, type: "connected", id: "-1075253572", manufacturer: "AKAI", name: "MPKmini2", …}
```

**Comment by cotejp** [comment] 2017-10-17 02:50
@belm0 I was able to reproduce the problem on Chrome 61/Windows 10. It seems to be coming from upstream. I'll have to do more tests to be sure but as far as I can tell Chrome is not firing those events at all... I'll try it on Linux and macOS and see if there's a difference. Which platform are you on?

Thanks for reporting.

**Comment by belm0** [comment] 2017-10-17 03:03
I'm seeing it on OS X Sierra with Chrome 61.

**Comment by cotejp** [comment] 2017-10-18 21:02
After re-reading the spec and looking at various use cases, I am concluding that it would be more logical if the `connected` and `disconnected` events only fired when a device is actually being connected or disconnected. If you load a page while devices are already connected, it should not fire the connected event. There's no real point to it anyway since we can simply look at `WebMidi.inputs` and `WebMidi.outputs` to know what's available.

Obviously, if a device is added or removed later on, the events will be fired. I commited a new [version](https://raw.githubusercontent.com/cotejp/webmidi/master/src/webmidi.js) which works in this way. Perhaps you can try it and let me know what you think.

P.S. I need to do a few more tests before actually releasing it on NPM.

**Comment by belm0** [comment] 2017-10-18 21:28
The behavior up until now was convenient, since I could just implement the ```connected``` event to handle both the case where device is already connected at init and where device is connected afterwards.

Would you share some background on the decision to change semantics?

**Comment by cotejp** [comment] 2017-10-18 23:20
I totally understand your position. Let me think about it a little...

**Comment by cotejp** [comment] 2017-10-19 00:35
Okay, I think I found a way to meet your needs. Can you try the new [latest committed version](https://raw.githubusercontent.com/cotejp/webmidi/master/src/webmidi.js) to confirm it works for you?

This version triggers `connected` events for both inputs and outputs.

**Comment by cotejp** [comment] 2017-10-19 00:38
If you still want some background info, you can check the [comments I added for myself](https://github.com/cotejp/webmidi/blob/master/src/webmidi.js#L477) in the code.

**Comment by cotejp** [comment] 2017-10-27 00:57
I have not heard back from OP so I'm going to assume that the fix is satisfactory and close this bug report.

**Closed by cotejp** 2017-10-27 00:57 UTC
Labels: bug

**Comment by belm0** [comment] 2017-12-04 06:49
I was able to confirm this fix finally, thank you.
