### ISSUE TITLE
npm install webmidi contains no JS files

### ISSUE THREAD

**Issue by jasonpang** [cotejp/webmidi#1] opened 2015-11-21 11:12 UTC
Perhaps I'm installing it wrong, but `npm install webmidi` seems to give me a folder without any JS files in it:

![image](https://cloud.githubusercontent.com/assets/1015970/11318232/bfe01454-8ffd-11e5-9013-d8b765a32a41.png)

**Comment by cotejp** [comment] 2015-11-21 15:42
I can confirm this issue. This is very odd as it was working before. It's probably related my publishing workflow. I'll check it out. Meanwhile, you can install manually or via Bower.

**Comment by cotejp** [comment] 2015-11-21 18:04
I republished the lib two more times and the problem went away. I'm guessing the problem is related to the recent switch from an alpha version label to a beta version label. I've read some people had issues with that but I'm not 100% sure this is the root cause. Tell me if it works out for you.

**Comment by jasonpang** [comment] 2015-11-21 18:13
Thank you for solving that so quickly! I'll report back if there are any problems.

**Comment by cotejp** [comment] 2015-11-21 18:15
No problem. I'm going to close this issue for now. Please open a new issue if it surfaces again.

**Closed by cotejp** 2015-11-21 18:15 UTC
